# [ru-crescent]
# repo = "Crescent-Corporation/LimbusCompanyBusRUS"
# name = "CresCorp"
# authors = ["..."]
# flag = "RU"
# icon = "https://github.com/Crescent-Corporation/LimbusCompanyBusRUS/raw/LC_branch_ORIGINAL/Localize/Readme/Crescent_Button.png"
# format = "compatible"

# [[ru-crescent.fonts]]
# url = "https://github.com/kimght/LimbusFonts/releases/download/v0.1.0/pretendard_light.otf"
# hash = "86bec888f8bcb9e9e76e433a120c5962"
# name = "pretendard_light.otf"

[ru-mtl]
repo = "kimght/LimbusCompanyRuMTL"
name = "MTL"
authors = ["kimght", "DAFTPUSiK", "x1bViolet", "Babkaebpmg", "KJHater"]
flag = "RU"
icon = "https://github.com/kimght/LimbusCompanyRuMTL/raw/main/data/images/logo.png"
format = "new"
localization_asset = "localize_files.zip"

[[ru-mtl.fonts]]
url = "https://github.com/kimght/LimbusFonts/releases/download/v1.6.0/merged_font.ttf"
hash = "cc1f83f52bd357201db884fd5400072c"
name = "merged_font.ttf"
