[ru-CresCorp]
repo = "Crescent-Corporation/LimbusCompanyBusRUS"
name = "CresCorp"
authors = ["Knightey", "Disaer", "Mellison", "Mermera"]
flag = "RU"
icon = "https://github.com/Crescent-Corporation/LimbusCompanyBusRUS/raw/LC_branch_ORIGINAL/Localize/Readme/Crescent_Button.png"
format = "new"
fonts = []

[[ru-CresCorp.fonts]]
url = "https://github.com/kimght/LimbusFonts/releases/download/v1.8.0/merged_font.ttf"
hash = "b8c47fe4c36a080587b57e5c31fa7fb9"
name = "Context/ContextFont.ttf"

[[ru-CresCorp.fonts]]
url = "https://github.com/kimght/LimbusFonts/releases/download/v1.8.0/merged_font.ttf"
hash = "b8c47fe4c36a080587b57e5c31fa7fb9"
name = "Title/TitleFont.ttf"

[ru-mtl]
repo = "kimght/LimbusCompanyRuMTL"
name = "MTL"
authors = ["kimght", "DAFTPUSiK", "x1bViolet", "Babkaebpmg", "KJHater"]
flag = "RU"
icon = "https://github.com/kimght/LimbusCompanyRuMTL/raw/main/data/images/logo.png"
format = "new"
localization_asset = "localize_files.zip"

[[ru-mtl.fonts]]
url = "https://github.com/kimght/LimbusFonts/releases/download/v1.8.0/merged_font.ttf"
hash = "b8c47fe4c36a080587b57e5c31fa7fb9"
name = "Context/ContextFont.ttf"

[[ru-mtl.fonts]]
url = "https://github.com/kimght/LimbusFonts/releases/download/v1.8.0/merged_font.ttf"
hash = "b8c47fe4c36a080587b57e5c31fa7fb9"
name = "Title/TitleFont.ttf"

[hant-LTM]
repo = "LimbusTraditionalMandarin/storyline"
name = "Limbus Traditional Mandarin"
authors = [
  # Lead
  "薯條", 
  # Managers
  "Traxton", 
  "小睡一夏", 
  "まぅSmallYuan", 
  "tool-jx3", 
  "未知未知",
  # Proofreaders
  "：이상",
  "阿茶同學",
  "十",
  # Translators
  "동랑",
  "Dango-moshi",
  "Linne1025",
  "蜜絲",
  "동백.",
  "ulofsix"
]

flag = "LTM.png"
icon = "https://avatars.githubusercontent.com/u/200600060"
format = "new"

[[hant-LTM.fonts]]
url = "https://github.com/LimbusTraditionalMandarin/font/releases/download/1744630853/SarasaGothicTC-Bold.ttf"
hash = "44563efaea921914d58e42bac4495881"
name = "Context/ContextFont.ttf"

[[hant-LTM.fonts]]
url = "https://github.com/LimbusTraditionalMandarin/font/releases/download/1744630853/SarasaGothicTC-Bold.ttf"
hash = "44563efaea921914d58e42bac4495881"
name = "Title/TitleFont.ttf"
