selected_source = "github"

[installed]

[sources.github]
name = "Github"
url = "https://gist.githubusercontent.com/kimght/322a2779922ab5a5f96ff7f7dc3f8e82/raw/localizations.json"

# game_directory = ""
# language = ""