services:
  update-gist:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./update_gist/localizations.toml:/app/localizations.toml
    restart: always
    env_file:
      - .env
