name: Update Localizations Gist

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r scripts/update_gist/requirements.txt

      - name: Run update script
        env:
          GITHUB_GIST_ID: ${{ secrets.GIST_ID }}
          GITHUB_GIST_OWNER: ${{ secrets.GIST_OWNER }}
          GITHUB_TOKEN: ${{ secrets.GIST_UPDATE_TOKEN }}
        run: python scripts/update_gist/main.py 